### ISSUE TITLE
2_03: Cape Verdean Creole of São Vicente

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#131]
- Table 4
  - leftmost column should be small caps
- Table 5
  - leftmost column should be italics (except for brackets and their content)
- spacing after sections 1, 3, 4, 5, 6, 8, 10 too small
- Glossed text
  - should not be a numbered section

**Comment by SusanneMichaelis** [comment]
Text neben Table 4 muss UNTER Table 4.
