### ISSUE TITLE
APICS Chapters 131-335 links are broken

### ISSUE THREAD

**Issue by ekmakhlina** [clld/apics#572]
Hi!

Thanks a lot for APICS, it's a great project and important source for my bachelor thesis.

Not sure if it was intended, but inks from the feature page (https://apics-online.info/parameters) to the chapters lead to 404 pages, e. g. https://apics-online.info/parameters/159.chapter.html 
Look like it is an issue for al the chapters from 131 to 335.

**Comment by xrotwang** [comment]
Thanks for letting us know! The links shouldn't be there at all, since there are only chapter texts (from the APiCS Atlas) for the "primary" features up to number 130. I'll make sure the broken links won't show up anymore.

**Comment by ekmakhlina** [comment]
Thanks! Though it looks like all features 131-335 are gone now, not only links to the chapters, but values too, was it intended?
