### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#58]
- ~~font not Times (or similar)~~
- ~~consistent spacing in numbered sections (e.g. 1.Introduction -> 1. Introduction) (chapters are currently very different and have either many small spaces, one big space, or no space at all)~~
- Edit 1
  - ~~text not justified (at least for most survey chapters)~~
  - ~~angle brackets are not wide enough, e.g. < vs ⟨~~
  - ~~alignment for most examples not right~~
  - ~~wrong colon for indicating vowel length, shouldn't be the regular but the triangular colon~~
- Edit 2
  - ~~most footnotes on a section heading have very huge font sizes~~
  - ~~many notes are underlined~~
  - ~~grammatical labels inside or outside of examples/tables are often in caps and not small caps~~
- Edit 3
  - nothing happens when I click a reference inside of a footnote
  - ~~footnotes in tables shouldn't be numbers but letters~~
  - for references in the form of "Name 2001, 2002" only Name 2001 gets a link
  - ~~in tables of phoneme inventories, the phonemes should be centered~~
- Edit 4
  - ~~add language link to reference type of "see Matthews & Li, this volume" (or maybe rather delete it since language link is probably nearby anyway?!)~~
- Edit 5
  - maps not equal in size; stretch them to fit the size of the table?!
  - ~~in primary text of examples, "[…]" should not be italic~~
  - some footnote texts are placed to far left (and therefore outside of the box)

**Comment by xrotwang** [comment]
But do we really want Times (i.e. a serif font, I guess)? For the web, often sans-serif fonts are assumed a better choice - and using the same font as for all other pages on the site seems a good argument against Times or similar as well.

**Comment by nicobenz** [comment]
Serif fonts have a better readability for longer texts, but I agree that we should keep the font consistent across the site.

**Comment by xrotwang** [comment]
largely fixed. Remaining issues will be addressed on a case-by-case basis.
