### ISSUE TITLE
3_07: Juba Arabic

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#68]
- whole text
 - often reference to Southern Sudan, which isn't the correct term anymore; should be substituted with South Sudan
- 1 Introduction
 - last sentence shouldn't have its own paragraph; should be just a regular part of the previous paragraph
- Examples
 - they all seem to have a table-ish shape (each part is separated by a visible line)
 - numbering starts randomly in the middle of the text
- Table 4
 - top row should read: Prox, Dist; left column should read: Singular, Plural
- 5.6 Numerals
 - should have an own table
- Table 5, 6, 7
 - left column should be italics
- 6.5 Negation
 - text is oddly positioned right next to some examples

**Comment by xrotwang** [comment]
Both, the table-like example formatting and the numbering starting in the middle of the text are present already in the source document.
