### ISSUE TITLE
3_09: Sri Lankan Malay

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#70]
- headings font size is unequal
- Table 3
  - leftmost column in small caps
- 4 2 2 Dative/allative case
  - second reference in first sentence not linked
- ex. 7
  - PERF in gloss should be PRF
- 4 4 Adjectives
  - reference in last sentence not linked
- lines above ex. 21-27 respectively
  - no small caps but with a dash in front

**Comment by xrotwang** [comment]
The line above ex. 21-27 are in all-caps in the source doc as well.
