### ISSUE TITLE
2_23: Louisiana Creole

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#75]
- 4 Phonology
 - tilde should be on top of the respective phoneme left to it and not beside it (this also applies to table 1)
 - j with tilde should not have a dot
- Table 5
 - no dots in front of the items

**Comment by xrotwang** [comment]
The [j with tilde](http://phoible.org/parameters/8E5C34586795133BB63747F3E0FE57B9) may well have a dot - depending on the font used to render it.

**Comment by xrotwang** [comment]
The "dots" in Table 5 are present in the source file, too.
