### ISSUE TITLE
1_26: Negerhollands

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#79]
- 3 Sociolinguistic situation
 - heading placed too far left
 - Figure 1 badly misplaced; should be aligned like a square and not under each other
- 5 Noun phrase
 - de Josselin de Jong 1926 is abbreviated as dJdJ 1926 (or DJDJ 1926) from this point onwards; should be linked as well

**Comment by Chrstph** [comment]
Überschrift "9. Interrogative construction sand topicalization" zu weit links und fehlt im Inhaltsverzeichnis
