### ISSUE TITLE
2_18: Papiamentu

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#84]
- missing link for several citations
- 2 Sociohistorical background
  - wrong reference link for Emmanuel & Emmanuel 1970 (also not in list of references)
- multiple cited references are missing: Hartog 1961, Postma, Goslinga, Buddingh, Emmanuel & Emmanuel

**Comment by xrotwang** [comment]
References seem to be missing already in the source doc file, at least Hartog 1961 - which I just checked.
