### ISSUE TITLE
Bislama audio issue

### ISSUE THREAD

**Issue by dohliam** [clld/apics#89]
The audio player on the [Bislama page](http://apics-online.info/contributions/23) does not seem to be working (i.e., nothing happens when the play button is pressed).

Going directly to the [audio file](http://edmond.mpdl.mpg.de/imeji/file/4WkY1hHhw8iEuNQ4/d2/61/85/39-b9bd-48cb-8826-59a38368fa12/0/original/eb8c3c9e274c80bad98984abac2270e0.mp3) doesn't help, and downloading the file reveals that it is only 262 bytes long. There is what appears to be a truncated mp3 header, though -- it looks like the upload might have been cut off mid-transfer.

Tested on recent versions of Firefox and Chrome.

**Comment by xflr6** [comment]
Thanks.
@xrotwang Looks like the file was already truncated in the source repo (other mp3s look okay):
https://github.com/clld/apics-data/blob/master/files/contribution/23/23-gt.mp3

**Comment by dohliam** [comment]
@xrotwang The audio appears to still be missing -- is the original audio file no longer available?
