### ISSUE TITLE
2_12: Sri Lanka Portuguese

### ISSUE THREAD

**Issue by nicobenz** [clld/apics#92]
- 4 Phonology
  - j with tilde not displayed correctly (third-last sentence of this chapter)
- Table 8: Negative markers
  - missing completely?!

**Comment by Chrstph** [comment]
4. Phonology: "[lɛːɲa ~ lɛː̃ɐ] " ̃ falsch dargestellt (erscheint als Kästchen)
8. Complex sentences: Absatz "Quotative constructions use the quotative [...]" erscheint als Link
